/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Omar
 */
public class RiskGame extends javax.swing.JFrame
{

    /**
     * Creates new form RiskGame
     */
    public RiskGame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioButton_greedy = new javax.swing.JRadioButton();
        radioButton_miniMax = new javax.swing.JRadioButton();
        radioButton_Astar = new javax.swing.JRadioButton();
        radioButton_realTime = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        radioButton_miniMax1 = new javax.swing.JRadioButton();
        radioButton_Astar1 = new javax.swing.JRadioButton();
        radioButton_realTime1 = new javax.swing.JRadioButton();
        radioButton_greedy1 = new javax.swing.JRadioButton();
        radioButton_human = new javax.swing.JRadioButton();
        radioButton_aggressive = new javax.swing.JRadioButton();
        radioButton_passive = new javax.swing.JRadioButton();
        radioButton_pacifist = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(89, 50, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("Select Player 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 153));
        jLabel3.setText("Start Game");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        buttonGroup1.add(radioButton_greedy);
        radioButton_greedy.setText("Greedy Agent");
        jPanel1.add(radioButton_greedy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        buttonGroup1.add(radioButton_miniMax);
        radioButton_miniMax.setText("MiniMax Agent");
        jPanel1.add(radioButton_miniMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        buttonGroup1.add(radioButton_Astar);
        radioButton_Astar.setText("A* Agent");
        jPanel1.add(radioButton_Astar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        buttonGroup1.add(radioButton_realTime);
        radioButton_realTime.setText("RealtTime A* Agent");
        jPanel1.add(radioButton_realTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 102));
        jLabel4.setText("Select Player 1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 140, 20));

        buttonGroup1.add(radioButton_miniMax1);
        radioButton_miniMax1.setText("MiniMax Agent");
        jPanel1.add(radioButton_miniMax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        buttonGroup1.add(radioButton_Astar1);
        radioButton_Astar1.setText("A* Agent");
        jPanel1.add(radioButton_Astar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        buttonGroup1.add(radioButton_realTime1);
        radioButton_realTime1.setText("RealtTime A* Agent");
        jPanel1.add(radioButton_realTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        buttonGroup1.add(radioButton_greedy1);
        radioButton_greedy1.setText("Greedy Agent");
        jPanel1.add(radioButton_greedy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        buttonGroup1.add(radioButton_human);
        radioButton_human.setText("HumanAgent");
        jPanel1.add(radioButton_human, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        buttonGroup1.add(radioButton_aggressive);
        radioButton_aggressive.setText("Aggressive Agent");
        jPanel1.add(radioButton_aggressive, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        buttonGroup1.add(radioButton_passive);
        radioButton_passive.setText("Passive Agent");
        jPanel1.add(radioButton_passive, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        buttonGroup1.add(radioButton_pacifist);
        radioButton_pacifist.setText("Pacifist Agent");
        jPanel1.add(radioButton_pacifist, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RiskGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RiskGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RiskGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RiskGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RiskGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioButton_Astar;
    private javax.swing.JRadioButton radioButton_Astar1;
    private javax.swing.JRadioButton radioButton_aggressive;
    private javax.swing.JRadioButton radioButton_greedy;
    private javax.swing.JRadioButton radioButton_greedy1;
    private javax.swing.JRadioButton radioButton_human;
    private javax.swing.JRadioButton radioButton_miniMax;
    private javax.swing.JRadioButton radioButton_miniMax1;
    private javax.swing.JRadioButton radioButton_pacifist;
    private javax.swing.JRadioButton radioButton_passive;
    private javax.swing.JRadioButton radioButton_realTime;
    private javax.swing.JRadioButton radioButton_realTime1;
    // End of variables declaration//GEN-END:variables
}
